multitenancyEnabled: false

tempo:
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces

server:
  http_listen_port: 3200

ingester:
  trace_idle_period: 10s
  max_block_duration: 5m

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

persistence:
  enabled: true
  size: 10Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
