apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: observability-rules
  namespace: observability
spec:
  groups:
    - name: kubernetes.rules
      rules:
        - alert: NodeNotReady
          expr: kube_node_status_condition{condition="Ready",status="true"} == 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Node not ready"

        - alert: PodCrashLooping
          expr: rate(kube_pod_container_status_restarts_total[5m]) > 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Pod restarting frequently"

        - alert: DeploymentReplicasMismatch
          expr: kube_deployment_status_replicas_available != kube_deployment_spec_replicas
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Deployment replicas mismatch"