mode: deployment
replicaCount: 1

image:
  repository: otel/opentelemetry-collector-contrib
  tag: "0.128.0"

config:
  extensions:
    health_check:
      endpoint: 0.0.0.0:13133

  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

  processors:
    batch: {}

  exporters:
    debug:
      verbosity: detailed
    otlp/tempo:
      endpoint: app-observability-tempo-minikube:4317
      tls:
        insecure: true

  service:
    extensions: [health_check]
    pipelines:
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [debug]
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [debug]
      logs:
        receivers: [otlp]
        processors: [batch]
        exporters: [debug]

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
