apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-observability-minikube
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 68.2.1
      helm:
        skipCrds: true
        valueFiles:
          - $values/k8s/observability/kube-prometheus-stack/values/minikube.yaml

    - repoURL: https://github.com/SergioCMDev/Infra-AWS-EKS-Python
      targetRevision: HEAD
      ref: values

    - repoURL: https://github.com/SergioCMDev/Infra-AWS-EKS-Python
      targetRevision: HEAD
      path: k8s/observability/kube-prometheus-stack/alerts

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - PruneLast=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
